# Generated by Django 4.2.3 on 2023-07-16 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_contact_alter_news_options_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
