# Generated by Django 4.2.3 on 2023-07-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
