# Generated by Django 4.2.3 on 2023-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='som_char', max_length=200),
            preserve_default=False,
        ),
    ]
